### PR TITLE
Adding public download button option

### PR DESCRIPTION
**Pull request by si1k**
Hey! Just found this project and absolutely dig it! 

I wanted to add an optional allow public download button and ENV setting. I tried to follow your existing patterns and make use of the existing components but there was a few I was not sure if I should just make it simpler or leverage your current loading components. 

Please let me know any changes. 

The goal is to add an ENV that can enable a public download icon making saving for viewers a bit easier. No permission changes are required since a clever user would have access to the source link anyway.

### CODE REVIEW

**Comment by sambecker** [comment]
As you may know, this is offered currently as an admin feature:

CleanShot 2024-08-21 at 12 13 35@2x

Can you expand a bit on why you would want to make this public (vs private)?

If we did offer it, it seems like it could continue living in a ••• menu that was publicly accessible?

**Comment by si1k** [comment]
Yes, I did know it was an admin feature. For my purposes, I am sharing images from a conference that I want people to be able to download full resolution. The full res image url is exposed in source so they can already find it, this just makes is easier. 

The project is kind of a Flickr clone without the social media aspect so the public download feels like it fits. 

I am not opposed to making it a dot menu though it felt a bit odd having a menu with just one item in the drop down. 

Would you want to move the share there as well so it is two items? 

Also, random question - why is the invalidation only set to 1hr for images seems odd since the images would theoretically never or rarely change unless deleted.

**Comment by sambecker** [comment]
> Would you want to move the share there as well so it is two items?

Feel like this would be a good thing to try, and reasonable for people wanting this type of power user feature?

> Why is the invalidation only set to 1hr for images

Agreed, this should not be the case! Where are you seeing that? `next/image` should have a very generous TTL. Possibly OG generation?

**Comment by sambecker** [comment]
> Why is the invalidation only set to 1hr for images

In the case of og image caching, just extended revalidation window with https://github.com/sambecker/exif-photo-blog/commit/56eec8d1fa624c78c4a9c64ce26e2688f83c28e7

**Comment by sambecker** [comment]
Closing in favor of #149

**Comment by sambecker** [comment]
Merged! Let me know if you encounter any issues.

**Comment by si1k** [comment]
@sambecker Thank you! Excited to check it out! 

Priorities pulled me away, thank you so much for finalizing this!

**Comment by sambecker** [comment]
🙌

**Pull request closed without merging**
