### PR TITLE
Offer configuration to enable grid-based homepage

### PR DESCRIPTION
**Pull request by sambecker**
- Allow grid-first root through environment variable `NEXT_PUBLIC_GRID_HOMEPAGE`
- Resort core nav icons based on configuration
- Introduce new `/feed` page

Requested #113

### CODE REVIEW

**Comment by ghenry** [comment]
Nice! How do I redeploy on vercel with a new version again?

**Comment by sambecker** [comment]
You should be able to add the new environment variable on Vercel, then sync your forked repo from GitHub. 

If you don't have a forked repo, you might want to create one, in order to keep receiving updates. Once you've done that you should be able to go to your Vercel project and change the repo connection.

**Comment by ghenry** [comment]
Ah, OK. Thanks. I just followed the main README links which I think forks
your repo?

Will be nice to not always have to share gavinhenry.com/grid now 😜😎

Love this project!

**Comment by sambecker** [comment]
Nice!

If your repo is a fork, should be able click "Code" and then "Update branch."

CleanShot 2024-06-30 at 09 51 49 2@2x

**Comment by sambecker** [comment]
Just added some basic fork instructions to the README FAQ in case it's helpful @ghenry:
https://github.com/sambecker/exif-photo-blog?tab=readme-ov-file#how-do-i-receive-template-updates

**Comment by ghenry** [comment]
Thanks. Will have a look when I get back from holiday.

**Pull request merged**
